### PR TITLE
perform_async method

### PR DESCRIPTION
**Pull request by eritiro**
added a perform_async method to enqueue new requests.

### CODE REVIEW

**Comment by sschepens** [comment]
@eritiro Hey! sorry I don't know how i missed this!
What's you're requirement for this?

**Comment by eritiro** [comment]
hey @sschepens... well, we have an app that enqueues actions that require some time to be executed (about 20 seconds) and in the same app (same code, different instances) we have a background job that consumes those request and processes the action. the issue with your gem is that it doesn't support enqueuing requests so that's why I added that method.

**Comment by sschepens** [comment]
@eritiro is this a rails app? I could have a go at implementing an ActiveJob adapter if that's more useful

**Comment by eritiro** [comment]
ok. cool! yes it is.

**Comment by bglusman** [comment]
@sschepens / @eritiro seems like neither of these ever happened?  Looking at moving over to toiler cause of shoryuken memory leak, but we currently use perform_async also.  Could switch to using active job I think pretty easily, but definitely would like one of these!  Maybe we can do it ourselves and PR, but want to make sure its not already in progress or something, or if I'm missing how to do this,

**Comment by sschepens** [comment]
@bglusman I have been pretty busy, please go ahead and make a pull request!

**Comment by sschepens** [comment]
@bglusman Toiler has taken a very different road from Shoryuken, please let me know how the migration works and if you happen to need any extra features or anything.
As always, PRs are always appreciated.
Cheers!

**Comment by bglusman** [comment]
@sschepens thanks... still evaluating whether and how to make switch, but some weirdness/issues with toiler so far... it checks to make sure concurrent isn't already loaded, which is an issue since other gems also rely on concurrent-ruby... at first I thought the only one was capybara, and I moved that to require: false, and explicitly require in test helper, but it looks like sprocket is also relying on it, and weirdly, there's a different load order on mac vs linux, so it loads OK there (as in toiler loads first on mac and so is able to check ::Concurrent is undefined in require), but on linux it seems sprockets has already been loaded and it fails because it's already defined.  Some other minor issues that are probably my fault, but the issues with concurrent-ruby seem likely to effect others since sprockets is standard in rails and capybara is common.

**Comment by sschepens** [comment]
@bglusman I haven't found any issues running toiler on Linux, that's odd. It used to check if Concurrent was already required because requiring it before daemonizing used to break things, I believe that issue was fixed, I have to check if that is still necessary.

> I'm also a little confused by the class-var suggestion, what exactly is getting instantiated and how/what is shared across threads? it seems like instance variables I memoize are somehow getting set once on start and then being found by every subsequent invocation of the worker, not just within the same message.... can't imagine why/how that would/could happen! I have a workaround but it makes me nervous.

I believe this behavior is similar to how Shoryuken works, maybe I am mistaken, Workers are instantiated only once at start of the program and the amout depends on the concurrency specified. This workers belong to a pool and alternate on taking messages.
Did you intend for workers to be created for every message received?

You can check the code, it's really simple its just a few classes with very little code, all the magic comes from Concurrent Ruby.

**Comment by bglusman** [comment]
I'll take a look, but even if only initialized once per worker, at 25
concurrency that should be 25 instances no? I'm seeing apparently one
instance shared across all processes, definitely not how shoryuken behaved.

On Sun, Jun 26, 2016 at 2:08 PM sschepens <notifications@github.com> wrote:

> @bglusman <https://github.com/bglusman> I haven't found any issues
> running toiler on Linux, that's odd. It used to check if Concurrent was
> already required because requiring it before daemonizing used to break
> things, I believe that issue was fixed, I have to check if that is still
> necessary.
>
> I'm also a little confused by the class-var suggestion, what exactly is
> getting instantiated and how/what is shared across threads? it seems like
> instance variables I memoize are somehow getting set once on start and then
> being found by every subsequent invocation of the worker, not just within
> the same message.... can't imagine why/how that would/could happen! I have
> a workaround but it makes me nervous.
>
> I believe this behavior is similar to how Shoryuken works, maybe I am
> mistaken, Workers are instantiated only once at start of the program and
> the amout depends on the concurrency specified. This workers belong to a
> pool and alternate on taking messages.
> Did you intend for workers to be created for every message received?
>
> You can check the code, it's really simple its just a few classes with
> very little code, all the magic comes from Concurrent Ruby.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sschepens/toiler/pull/1#issuecomment-228614135>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAGb5BK6pMWitpugSIXj8ZS_i2ghPdQxks5qPsAwgaJpZM4E8Z3H>
> .
>
-- 
-Brian

**Comment by bglusman** [comment]
Also, for the record, yes, I assumed and still woukd preder over object instance per message :-)

**Comment by bglusman** [comment]
If it's useful I can probably create a trivial example worker or rep that reproduces the surprising behavior by the way, but it was confusing to debug, because my workers turn messages into ActiveRecord objects, and I was artificialy creating hundreds of messages, and watching to see the number of DB entries go up, and I'd see it go up 1 and just stop...which made no sense, but eventually I realized that because I was memoizing part of the object during message parsing and validation with `@var ||= Model.new(message)`, the first object would be created but then every other message would already have var initialized with the first object!  Easy enough to fix, and perhaps what I should do is not use the worker class/instance to contain any instance logic and just always make a new PORO that does all the work for a message passed in, but it was fairly confusing and counterintuitive, and I still don't understand how a single instance is shared across multiple threads, though based on the behavior I saw that seems to be what's happening.  Just had a look at the code and still don't understand, but happy to help debug or figure out what if anything should/could change.

**Comment by sschepens** [comment]
@bglusman Toiler uses Concurrent Ruby for Actors, unlike Shoryuken which uses Celluloid.
Each Celluloid Actor has and belongs to only one thread, but in Concurreny Ruby, Actors do not belong to any particular thread, they are just scheduled to run in a thread pool.
Maybe this is causing your issue?

**Comment by sschepens** [comment]
@bglusman I have checked and Shoryuken [creates a new Worker](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/default_worker_registry.rb#L23) for every new message received.
Maybe Toiler should do the same thing, but this breaks backwards compatibility, maybe it should belong to a new mayor release.

**Comment by bglusman** [comment]
Yup, I was aware because that's how or old code works!  Agree, implementing as an active job interface and the right way to go, though in such a way that Bob rails code can use without active job as a hard dependency would be good, that's how delayed job works, unsure about shoryuken.  Maybe I can help!  Thanks!

**Comment by bglusman** [comment]
@sschepens I was thinking maybe I/we can help you with this change, but a) I'm not sure how easy it will be, and b) not sure if you've already started or have a strong sense of how you want to make the change to a) be worker instance per message, and b) support active job API.  We could move ahead using toiler as it is, but if we have ability and time to give back and help out, and use the new interface sooner, that'd be nice! Or if you anticipate doing it yourself soon we can just wait and use the new version if you think it's less than a week or so away... but no idea how big a change or what your bandwidth is like.  If want to discuss or coordinate how/if we can help, shoot me an email at my github email to discuss!

**Comment by sschepens** [comment]
@bglusman 
a) Instantiating a new worker per message is a easy job and I'm testing it right now.
b) Supporting Active Job is hole new thing. I have been investigating a bit, creating an Active Job adapter should be fairly easy, what I have not yet seen is how to initiate toiler when a Rails app with toiler is started.

**Comment by bglusman** [comment]
@eritiro hey!  I haven't been super active in this project lately as I changed roles at work and it's been working well for us without changes, but curious if anything changed or just cleaning up issues?

**Comment by eritiro** [comment]
just cleaning up :) I've been busy with other stuff too :+1: 
thanks for asking

**Pull request closed without merging**
